services:
  frontend:
    image: ghcr.io/sondregronas/edugamedist
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      # Game installer locations
      - ./games/Windows:/app/public/games/Windows
      - ./games/Mac:/app/public/games/Mac
      - ./games/Linux:/app/public/games/Linux
      - ./games/Android:/app/public/games/Android

      # Configuration files
      - ./cfg:/app/public/cfg
      - ./cfg/views:/app/views/cfg  # (remove trailing /cfg if you want access to all views)
      # - ./cfg/css:/app/public/css

      # Persistent data, leave as is or map to a local folder
      - game_db:/app/db
      - game_covers:/app/public/img
    environment:
      - TITLE=Game Server
  db:
    image: nocodb/nocodb
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      # Persistent data, leave as is or map to a local folder
      - game_db:/usr/app/data/
      - game_covers:/usr/app/data/nc/uploads/noco/Games/Games/Cover
volumes:
  game_db:
  game_covers: