version: "3.3"
services:
  frontend:
    image: ghcr.io/sondregronas/edugamedist
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # Note, you can also bind any folder to a network share or different directories
      - ./games:/app/public/games

      # You can alternatively bind the platforms separately
      # ./Windows:/app/public/games/Windows
      # ./Mac:/app/public/games/Mac
      # ./Linux:/app/public/games/Linux
      # ./Android:/app/public/games/Android

      # /app/db is required for persistent storage
      - ./db:/app/db
      - ./db/nc/uploads/noco/Games/Games/Cover:/app/public/img

      # public/cfg = favicon and css overrides
      - ./cfg:/app/public/cfg
      # Uncomment for full CSS access
      # - ./cfg/css:/app/public/css

      # Choose between the header/footer/nav-menu, or the entire views folder (Advanced).
      - ./cfg:/app/views/cfg
      # - ./cfg/views:/app/views
    environment:
      - TITLE="Game Server"
  db:
    image: nocodb/nocodb
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./db:/usr/app/data/
