site_name: EduGameDist
docs_dir: docs

edit_uri: edit/main/docs/docs/
repo_name: EduGameDist
repo_url: https://github.com/sondregronas/EduGameDist



copyright: >
  EduGameDist: Simple game distribution for educational purposes.

theme:
    name: material
    custom_dir: overrides

    palette:  # Light/Dark Mode
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      primary: light blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      primary: light blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Light mode

    features:
        - content.code.annotate     # Add annotations to codeblocks (```code (1)``` 1. annotation)
        - navigation.indexes        # Attach docker.md to parent
        - navigation.tracking       # Automatically add #anchor to URL while scrolling
        - navigation.top            # Back to top button
        - navigation.prune          # Performance / size optimization
        - search.suggest            # Autocomplete results during search
        - search.highlight          # Highlight occurences inside clicked search result
        - search.share              # Share search URL button in text input

    logo: favicon.ico
    favicon: favicon.ico


extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sondregronas
      name: "@sondregronas"


markdown_extensions:
  # Essentials
  - meta                        # Load frontmatter (---\ntitle: Title\n---
  - attr_list                   # Add HTML attributes to anything (![image](link) { align=left })
  - nl2br                       # All linebreaks add <br> tags (starts new line on new lines...)
  - mdx_breakless_lists         # single linebreak required for lists, instead of two
  - pymdownx.magiclink          # Automatically wrap links to <a> tags https://google.com = <a href="https://google.com">https://google.com</a>

  # Features
  - footnotes                   # Citations (Zotero/Pandoc) ([^1], [^1]: Lorem ipsum)
  - admonition                  # Callout blocks > [!INFO], > [!WARNING], > [!VIDEO], > [!TECH], > [!CODE] (alt: !!! type)
  - pymdownx.details            # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#configuration
  - pymdownx.tasklist:          # - [ ] Task, - [x] Task completed
      custom_checkbox: true         # https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists

  # Code highlighting
  - pymdownx.superfences        # Code higlighting ```language\n code\n ```
  - pymdownx.highlight          # Syntax highlighting + superfences
  - pymdownx.inlinehilite       # Inline code highlighting

  # ^~= modifiers
  - pymdownx.caret              # ^^underline^^, ^superscript^ (H^2^O)
  - pymdownx.tilde              # ~~strikethrough~~, ~subscript~ (~2~OH)
  - pymdownx.mark               # ==mark text== (yellow marker)
  - pymdownx.betterem:          # **bold** *italic*, __bold__ _italic_
      smart_enable: all             # Both modifiers (* and _)

  # Extra
  - pymdownx.keys               # ++ctrl+alt+delete++
  - pymdownx.smartsymbols       # Convert special characters from markdown ((tm) = ™)
  - smarty                      # '' -> ‘’, "" -> “”, etc..
  - pymdownx.emoji:             # Emojis :smile: :tada:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - search                        # Search bar
    - callouts                      # Convert obsidian callouts to markdown format
    - roamlinks                     # Use WikiLinks
    - glightbox:                    # Lightbox! https://github.com/blueswen/mkdocs-glightbox
    - exclude:                      # Exclude pattern from site
        regex:
          - '.*\.(tmp|bin|tar)$'
    - minify:                       # Optimize load times
        minify_html: true

nav:
    - Home: index.md
    - Installation:
      - Docker: Installation/docker.md
      - Frontend: Installation/Frontend.md
      - Backend: Installation/Backend.md
      - Access: Installation/Access.md
    - Usage:
      - Adding games: Usage/Adding-games.md
      - Modifying games: Usage/Modifying-games.md
    - Gallery:
      - NocoDB: Gallery/Nocodb.md
    - Updating: Updating.md
    - Demo: /EduGameDist
