name: GitHub Pages

on:
  push:
    branches: [main]
    tags: [v*]
    paths-ignore:
      - 'README.md'
      - 'CONTIBUTING.md'
      - 'docker-compose.yml'

jobs:
  build-demo:
    name: Generate Demo
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Move Demo to src
        run: |
          cp .github/workflows/demo.js src/
          cp .github/workflows/demo-img.js src/

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: cd src && npm install

      - name: Build Demo
        run: cd src && node demo.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: src/demo
