name: GitHub Pages

on:
  push:
    branches: [main]
    tags: [v*]
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'docker-compose.yml'

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-gh-pages:
    name: Build GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Install application dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r src/requirements.txt

      - name: Build static demo
        run: python src/demo.py

      - name: Build documentation
        working-directory: docs
        run: |
          python -m pip install -r requirements.txt
          mkdocs build
          cp -R site/ ../src/demo/docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: src/demo

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
