name: GitHub Pages

on:
  push:
    branches: [main]
    tags: [v*]
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'docker-compose.yml'
      
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-gh-pages:
    name: Build GH Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Move Demo to src
        run: cp .github/workflows/demo.js src/

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./src
        run: npm install

      - name: Build Demo
        working-directory: ./src
        run: |
          node demo.js
          cp -R ../.github/workflows/demo-img/* demo/

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Build MkDocs
        working-directory: ./docs
        run: |
          pip install setuptools wheel
          pip install -r requirements.txt
          mkdocs build
          cp -R site/ ../src/demo/docs
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: src/demo

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
