name: GitHub Pages

on:
  push:
    branches: [main]
    tags: [v*]
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'docker-compose.yml'

jobs:
  build-gh-pages:
    name: Build GH Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Move Demo to src
        run: |
          cp .github/workflows/demo.js src/
          cp .github/workflows/demo-img.js src/

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./src
        run: npm install

      - name: Build Demo
        working-directory: ./src
        run: |
          node demo.js
          cp -R ../.github/workflows/demo-img/* demo/

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Build MkDocs
        working-directory: ./docs
        run: |
          pip install -r requirements.txt
          mkdocs build
          cp -R site/ ../src/demo/docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: src/demo
